### ISSUE TITLE
BUG: unable to refresh supporter info, 2.03.11.140, Win10

### ISSUE THREAD

**Issue by phluid61** [BattleScribe/Release#109]
I'm unable to refresh my supporter information on the Windows version of the application.

**What version of the app are you using?**

BattleScribe v2.03.11.140

**What version of Windows or macOS do you have?**

Windows 10

**What are the exact steps you go through to make the error happen?**

1. click 'Supporter' button
2. click 'Refresh'

A loading bar shows briefly, then a dialogue appears with the following error message:

~~~
Details:

  java.io.IOException: Failed to connect to URL: Bad Request (400)
  	at net.battlescribe.a.c.a.a(BattleScribe:113)
	at net.battlescribe.a.c.a.a(BattleScribe:79)
	at net.battlescribe.desktop.c.d.a(BattleScribe:292)
	at net.battlescribe.desktop.common.BattleScribeFrame$3.a(BattleScribe:267)
	at net.battlescribe.desktop.common.BattleScribeFrame$3.doInBackground(BattleScribe:262)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
~~~

**Comment by phluid61** [comment]
JRE 1.8.0_231

**Comment by phluid61** [comment]
I was able to sign out, then sign in again, and it retrieved my updated supporter info. After doing so, the 'Refresh' button no longer has an error.

Maybe my Google authentication token/whatever was invalidated, and I needed to re-authenticate. The HTTP 400 Bad Request response is unexpected in any case.

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147
