### ISSUE TITLE
"tokenResponse.accessToken must not be null" when refreshing

### ISSUE THREAD

**Issue by Jonskichov** [BattleScribe/Release#195]
https://www.reddit.com/r/BattleScribe/comments/gjrlrf/refresh_button_in_supporter_tab_raises/

 Version: v2.03.19.16

Details:  java.lang.IllegalStateException: tokenResponse.accessToken must not be null 	at net.battlescribe.desktop.common.b.b.a(BattleScribe:889) 	at net.battlescribe.desktop.common.BattleScribeWindowController$b.a(BattleScribe:723) 	at net.battlescribe.desktop.common.BattleScribeWindowController$b.call(BattleScribe:721) 	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source) 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Jonskichov** [comment]
duplicate: https://github.com/BattleScribe/Release/issues/193
